# GitHub Sponsors configuration
# Uncomment and configure as needed

# github: [andreashurst]
# patreon: your-patreon-username
# open_collective: your-opencollective-name
# ko_fi: your-kofi-name
# tidelift: npm/package-name
# community_bridge: project-name
# liberapay: your-liberapay-name
# issuehunt: your-issuehunt-name
# otechie: your-otechie-name
# lfx_crowdfunding: project-name
# custom: ["https://paypal.me/your-paypal", "https://example.com"]
