blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/andreashurst/claude-docker/discussions
    about: Ask questions or discuss ideas
  - name: Documentation
    url: https://github.com/andreashurst/claude-docker#readme
    about: Check the documentation first
