services:
  claude-flow:
    # Use pre-built image from Docker Hub
    image: andreashurst/claude-docker:latest-flow
    # Uncomment below for local development:
    # build:
    #   context: ..
    #   dockerfile: Dockerfile.flow

    working_dir: /var/www/html

    # Health check
    healthcheck:
      test: ["CMD", "claude", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

    # Network configuration
    extra_hosts:
      - "host.docker.internal:host-gateway"
    dns:
      - 8.8.8.8
      - 1.1.1.1

    # Volume mounts with proper permissions
    volumes:
      - ${PWD}:/var/www/html:cached
      - claude-flow-cache:/home/claude/.cache
      - claude-flow-npm:/home/claude/.npm
      - claude-flow-config:/home/claude/.config
      - claude-flow-deno:/home/claude/.deno
      - claude-flow-playwright:/home/claude/.cache/ms-playwright
      - /tmp/claude-mcp-config.json:/home/claude/.config/claude/claude_desktop_config.json:ro
      - ./docs:/var/www/html/docs:ro

    # Environment variables
    environment:
      - NODE_ENV=development
      - NPM_CONFIG_CACHE=/home/claude/.cache/npm
      - NPM_CONFIG_FETCH_TIMEOUT=300000
      - NPM_CONFIG_YES=true
      - CLAUDE_CONFIG_PATH=/home/claude/.config/claude
      - PATH="/home/claude/.deno/bin:$PATH"
      - DENO_INSTALL="/home/claude/.deno"
      - PLAYWRIGHT_BROWSERS_PATH=/home/claude/.cache/ms-playwright
      - PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=0
      - FRONTEND_URL=${FRONTEND_URL:-localhost:3000}
      - PROJECT_PATH=${PROJECT_PATH:-/var/www/html}
      - FRONTEND_PORT=${FRONTEND_PORT:-3000}

    # Interactive terminal
    stdin_open: true
    tty: true

    # Security options
    security_opt:
      - no-new-privileges:true

    # Restart policy: no automatic restart after reboot
    restart: "no"

    # Resource limits
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'

volumes:
  claude-flow-cache:
    driver: local
  claude-flow-npm:
    driver: local
  claude-flow-config:
    driver: local
  claude-flow-deno:
    driver: local
  claude-flow-playwright:
    driver: local