name: Docker Image CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    
    - name: Build and push claude-dev
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile.dev
        push: true
        tags: |
          andreashurst/claude-docker:latest-dev
          andreashurst/claude-docker:dev-${{ github.sha }}
    
    - name: Build and push claude-flow
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile.flow
        push: true
        tags: |
          andreashurst/claude-docker:latest-flow
          andreashurst/claude-docker:flow-${{ github.sha }}